version: 1.0.{build}
image: Visual Studio 2022

before_build:
  - nuget restore DabbaTrading.sln

build:
  project: DabbaTrading.sln
  verbosity: minimal

artifacts:
  - path: '**\bin\Release\**\*.dll'
    name: build-dll
