version: 1.0.{build}
image: Visual Studio 2022

build:
  project: DBTrading.sln   # ← Replace with your actual solution filename
  verbosity: minimal

artifacts:
  - path: '**\bin\Release\**\*.dll'
    name: build-dll
